# Generated by Django 4.1.3 on 2022-11-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('explains', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(max_length=10, null=True, unique=True)),
                ('account_number', models.CharField(max_length=16)),
                ('deposit_date', models.DateField(auto_now_add=True)),
                ('account_balance', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('explains', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(max_length=10, null=True, unique=True)),
                ('from_account_number', models.CharField(max_length=16)),
                ('to_account_number', models.CharField(max_length=16)),
                ('to_username', models.CharField(blank=True, max_length=20)),
                ('fund_transfer_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('explains', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(max_length=10, null=True, unique=True)),
                ('account_number', models.CharField(max_length=16)),
                ('withdraw_date', models.DateField(auto_now_add=True)),
                ('account_balance', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=16, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('account_balance', models.PositiveIntegerField(default=0)),
                ('account_type', models.CharField(max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
